-- MySQL Script generated by MySQL Workbench
-- 03/06/15 15:52:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Wechat
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Wechat` ;

-- -----------------------------------------------------
-- Schema Wechat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Wechat` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `Wechat` ;

-- -----------------------------------------------------
-- Table `Wechat`.`indexOption`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Wechat`.`indexOption` ;

CREATE TABLE IF NOT EXISTS `Wechat`.`indexOption` (
  `indexOptionId` INT NOT NULL,
  `indexOptionName` VARCHAR(45) NOT NULL,
  `indexOptionValue` VARCHAR(4500) NULL,
  `indexOptionDescription` VARCHAR(450) NULL,
  PRIMARY KEY (`indexOptionId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wechat`.`image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Wechat`.`image` ;

CREATE TABLE IF NOT EXISTS `Wechat`.`image` (
  `imageId` INT NOT NULL,
  `imageName` VARCHAR(45) NULL,
  `imageUrl` VARCHAR(450) NOT NULL,
  `imageDescription` VARCHAR(200) NULL,
  PRIMARY KEY (`imageId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wechat`.`otherPageOption`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Wechat`.`otherPageOption` ;

CREATE TABLE IF NOT EXISTS `Wechat`.`otherPageOption` (
  `otherPageOptionId` INT NOT NULL,
  `otherPageOptionPageName` VARCHAR(45) NOT NULL,
  `otherPageOptionName` VARCHAR(45) NOT NULL,
  `otherPageOptionval` VARCHAR(4500) NULL,
  `otherPageOptionDescription` VARCHAR(450) NULL,
  PRIMARY KEY (`otherPageOptionId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wechat`.`tool`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Wechat`.`tool` ;

CREATE TABLE IF NOT EXISTS `Wechat`.`tool` (
  `toolId` INT NOT NULL,
  `toolName` VARCHAR(45) NOT NULL,
  `toolUrl` VARCHAR(1500) NULL,
  `toolDescription` VARCHAR(1400) NULL,
  `toolOptionJsonVar` VARCHAR(450) NULL,
  PRIMARY KEY (`toolId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wechat`.`template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Wechat`.`template` ;

CREATE TABLE IF NOT EXISTS `Wechat`.`template` (
  `templateId` INT NOT NULL,
  `templateFolder` VARCHAR(45) NOT NULL,
  `templateName` VARCHAR(45) NULL,
  `templateDecription` VARCHAR(450) NULL,
  PRIMARY KEY (`templateId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wechat`.`page`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Wechat`.`page` ;

CREATE TABLE IF NOT EXISTS `Wechat`.`page` (
  `pageId` INT NOT NULL,
  `pageName` VARCHAR(45) NULL,
  `pageUrl` VARCHAR(45) NULL,
  PRIMARY KEY (`pageId`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
